apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: ghcr.io/morey-tech/demo-app
  newName: ghcr.io/morey-tech/demo-app
  newTag: eed979c9e9758feae1e457d7c48d06c87668650f
